name: Trigger auto deployment for aca-genaiwl

# When this action will be executed
on:
  # Allow manual trigger 
  workflow_dispatch:      

env:
  REGISTRY_NAME: "rpreucontinfraacr"                    # Replace with your ACR name
  IMAGE_NAME: "multiagents-web-api"
  RESOURCE_GROUP: "rg-chat-baseline-switzerlandnorth"            # Replace with your resource group
  CONTAINER_APP_NAME: "multiagents-web-api"        # Replace with your container app name
  CONTAINER_APP_ENVIRONMENT: "acaenv-genaiwl" # Replace with your container app environment

  AZURE_CLIENT_ID: ${{ secrets.ACAGENAIWL_AZURE_CLIENT_ID }}
  #AZURE_CLIENT_SECRET: ${{ secrets.ACAGENAIWL_AZURE_CLIENT_SECRET }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.ACAGENAIWL_AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.ACAGENAIWL_AZURE_TENANT_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ACAGENAIWL_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACAGENAIWL_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACAGENAIWL_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: rpreucontinfraacr.azurecr.io
          registryUsername: ${{ secrets.ACAGENAIWL_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACAGENAIWL_REGISTRY_PASSWORD }}
          containerAppName: aca-genaiwl
          resourceGroup: rg-chat-baseline-switzerlandnorth
          imageToBuild: rpreucontinfraacr.azurecr.io/aca-genaiwl:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


