name: Build and Deploy to Azure Container Apps

on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY_NAME: "rpreucontinfraacr"                    # Replace with your ACR name
  IMAGE_NAME: "multiagents-web-api"
  RESOURCE_GROUP: "rg-chat-baseline-switzerlandnorth"            # Replace with your resource group
  CONTAINER_APP_NAME: "multiagents-web-api"        # Replace with your container app name
  CONTAINER_APP_ENVIRONMENT: "acaenv-genaiwl" # Replace with your container app environment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Login via Azure CLI'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.ACAGENAIWL_AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.ACAGENAIWL_AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.ACAGENAIWL_AZURE_SUBSCRIPTION_ID }}

    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: 'Deploy to Azure Container Apps'
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --set-env-vars \
              AZURE_KEY="${{ secrets.AZURE_KEY }}" \
              AZURE_ENDPOINT_NAME="${{ secrets.AZURE_ENDPOINT_NAME }}"
